import { Language } from './translations';

/**
 * Prepares raw remedy or chatbot text for natural, clean speech synthesis.
 */
export const prepareTextForSpeech = (rawText: string, lang: Language): string => {
  if (!rawText) return '';

  let text = rawText
    // Remove markdown formatting symbols
    .replace(/[*#`_~🚨•]/g, ' ')
    // Replace hyphens between ingredient names and quantities with clean pause
    .replace(/\s+-\s+/g, ', ')
    // Replace step list numbers (e.g., "1. ", "2. ") with clean phrasing
    .replace(/(\d+)\.\s*/g, '$1. ')
    // Normalize newlines and consecutive spaces
    .replace(/\n+/g, '. ')
    .replace(/\s+/g, ' ')
    .trim();

  // Replace common remedy fraction units with spoken words for clarity
  if (lang === 'en') {
    text = text
      .replace(/\b1\/2\b/g, 'half')
      .replace(/\b1\/4\b/g, 'one quarter')
      .replace(/\btsp\b/gi, 'teaspoon')
      .replace(/\btbsp\b/gi, 'tablespoon')
      .replace(/\bmins?\b/gi, 'minutes');
  } else if (lang === 'hi') {
    text = text
      .replace(/\b1\/2\b/g, 'आधा')
      .replace(/\b1\/4\b/g, 'एक चौथाई')
      .replace(/\btsp\b/gi, 'छोटा चम्मच')
      .replace(/\btbsp\b/gi, 'बड़ा चम्मच')
      .replace(/\bmins?\b/gi, 'मिनट');
  } else if (lang === 'te') {
    text = text
      .replace(/\b1\/2\b/g, 'సగం')
      .replace(/\b1\/4\b/g, 'పావు')
      .replace(/\btsp\b/gi, 'టీస్పూన్')
      .replace(/\btbsp\b/gi, 'టేబుల్ స్పూన్')
      .replace(/\bmins?\b/gi, 'నిమిషాలు');
  }

  return text;
};

/**
 * Finds a matching installed SpeechSynthesisVoice that strictly matches the target language.
 * Returns NULL if no native voice for the requested language is found.
 * CRITICAL: Never return an English voice when target is Hindi or Telugu, as that causes
 * English TTS engines to ignore Devanagari/Telugu script and only pronounce digits.
 */
export const getStrictMatchingVoice = (lang: Language): SpeechSynthesisVoice | null => {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) return null;

  const voices = window.speechSynthesis.getVoices();
  if (!voices || voices.length === 0) return null;

  const targetLangPrefix = lang === 'hi' ? 'hi' : lang === 'te' ? 'te' : 'en';
  const keyword = lang === 'hi' ? 'hindi' : lang === 'te' ? 'telugu' : 'english';

  const matched = voices.find(v => {
    const vLang = v.lang.toLowerCase().replace('_', '-');
    const vName = v.name.toLowerCase();
    return vLang.startsWith(targetLangPrefix) || vName.includes(keyword);
  });

  return matched || null;
};

let currentAudio: HTMLAudioElement | null = null;

export const stopSpeech = () => {
  if (typeof window !== 'undefined') {
    if ('speechSynthesis' in window) {
      try {
        window.speechSynthesis.cancel();
      } catch (_) {}
    }
    if (currentAudio) {
      try {
        currentAudio.pause();
        currentAudio.currentTime = 0;
      } catch (_) {}
      currentAudio = null;
    }
  }
};

/**
 * Plays speech audio generated by the server-side multi-language TTS engine.
 */
const playServerTts = (
  cleanText: string,
  lang: Language,
  onStart?: () => void,
  onEnd?: () => void,
  onError?: (err: any) => void
) => {
  try {
    const audioUrl = `/api/tts?text=${encodeURIComponent(cleanText)}&lang=${lang}`;
    const audio = new Audio(audioUrl);
    currentAudio = audio;

    audio.onplay = () => {
      if (onStart) onStart();
    };

    audio.onended = () => {
      currentAudio = null;
      if (onEnd) onEnd();
    };

    audio.onerror = (e) => {
      console.warn('Server TTS audio playback error:', e);
      currentAudio = null;
      if (onError) onError(e);
      if (onEnd) onEnd();
    };

    const playPromise = audio.play();
    if (playPromise !== undefined) {
      playPromise.catch((err) => {
        console.warn('Audio play auto-play blocked or failed:', err);
        currentAudio = null;
        if (onError) onError(err);
        if (onEnd) onEnd();
      });
    }
  } catch (err) {
    console.error('Error initiating server TTS:', err);
    currentAudio = null;
    if (onError) onError(err);
    if (onEnd) onEnd();
  }
};

/**
 * Speaks text using Web Speech API with full multi-language support (English, Hindi, Telugu)
 * and seamless server-side TTS fallback when OS/browser lacks native language voice packs.
 */
export const speakText = (
  text: string,
  lang: Language,
  onStart?: () => void,
  onEnd?: () => void,
  onError?: (err: any) => void
) => {
  if (typeof window === 'undefined') {
    if (onError) onError('Window not defined');
    return;
  }

  stopSpeech();

  const cleanText = prepareTextForSpeech(text, lang);
  if (!cleanText) {
    if (onEnd) onEnd();
    return;
  }

  // Check if native browser TTS has a REAL matching voice for Hindi/Telugu
  const matchedVoice = getStrictMatchingVoice(lang);

  // CRITICAL FIX: If target language is Hindi or Telugu and NO native voice object is installed in browser,
  // DO NOT use window.speechSynthesis because English TTS engine will ignore non-ASCII script and only read numbers!
  // Use our server-side /api/tts endpoint instead for 100% full recipe pronunciation!
  const useServerTts = (lang === 'hi' || lang === 'te') && !matchedVoice;

  if (useServerTts) {
    playServerTts(cleanText, lang, onStart, onEnd, onError);
    return;
  }

  // Standard Web Speech API execution
  if ('speechSynthesis' in window) {
    try {
      window.speechSynthesis.cancel();
      window.speechSynthesis.resume();

      const defaultLangTag = lang === 'hi' ? 'hi-IN' : lang === 'te' ? 'te-IN' : 'en-US';

      // Split into clean sentence segments
      const sentences = cleanText
        .split(/(?<=[.।?!])\s+/)
        .map(s => s.trim())
        .filter(s => s.length > 0);

      if (sentences.length === 0) {
        if (onEnd) onEnd();
        return;
      }

      let hasStarted = false;

      const speakSentence = (index: number) => {
        if (index >= sentences.length) {
          if (onEnd) onEnd();
          return;
        }

        const sentenceText = sentences[index];
        const utterance = new SpeechSynthesisUtterance(sentenceText);

        if (matchedVoice) {
          utterance.voice = matchedVoice;
          utterance.lang = matchedVoice.lang;
        } else {
          utterance.lang = defaultLangTag;
        }

        utterance.rate = 0.88;
        utterance.pitch = 1.0;
        utterance.volume = 1.0;

        utterance.onstart = () => {
          if (!hasStarted) {
            hasStarted = true;
            if (onStart) onStart();
          }
        };

        utterance.onend = () => {
          speakSentence(index + 1);
        };

        utterance.onerror = (e) => {
          console.warn(`Speech synthesis error on sentence ${index}, falling back to server TTS`, e);
          stopSpeech();
          playServerTts(cleanText, lang, onStart, onEnd, onError);
        };

        window.speechSynthesis.resume();
        window.speechSynthesis.speak(utterance);
      };

      speakSentence(0);
      return;
    } catch (err) {
      console.warn('Web Speech API execution error, falling back to server TTS:', err);
    }
  }

  // Fallback to server TTS if SpeechSynthesis is not supported
  playServerTts(cleanText, lang, onStart, onEnd, onError);
};
